#Config file for BusinessSystem

#payouts are in % of total income
#if the employee each * total number of employees > total, employee total will be divided between all employees equally
#
#Payout values cannot exceed 100 in total!!!
payouts:
  business: 50
  owner: 10
  employee: 40